### ISSUE TITLE
How to set proxy for the plugin

### ISSUE THREAD

**Issue by NancyChunlan** [OSSIndex/ossindex-maven-plugin#12]
We are using the plugin in sandbox zone, and cannot access the https://ossindex.net directly.  After tried to set the proxy in maven settings.xml and also in environment variables, still it cannot be accessed.

Would you please guide us how to set the proxy?
Thanks!

**Comment by OSSIndex-Admin** [comment]
This is not currently supported. I will look into adding support shortly. Thanks for the report!

**Comment by NancyChunlan** [comment]
Thanks very much. We are looking forward to your updates.

**Comment by OSSIndex-Admin** [comment]
Hi. I will have some test code with proxy support soon, but I do not have a good way to fully test the code locally. I will be making a "SNAPSHOT" release and will send information on using this release so you can try it out.

**Comment by NancyChunlan** [comment]
Great.
We can do the verification once you finished the update. Thanks!

**Comment by OSSIndex-Admin** [comment]
So I know, does your proxy require username/password?

**Comment by OSSIndex-Admin** [comment]
Partial fix committed in c90b6ec61808ee0148ea989adc153ebbed74b79b
Bugfix in be6e6c24d91006f61e127304e440857bfe41a118

Added simple proxy support, where the proxy is defined in the settings.xml file. This uses the same settings as Maven itself. For example:

```
<settings>
...
  <proxies>
    <proxy>
      <id>Proxy Name</id>
      <active>true</active>
      <protocol>http</protocol>
      <username>proxyuser</username>
      <password>proxypass</password>
      <host>proxyhost</host>
      <port>80</port>
      <nonProxyHosts>local.net|some.host.com</nonProxyHosts>
    </proxy>
  </proxies>
</settings>
```
Note that currently the username and password are ignored.

This worked on a very simple local setup, but currently full testing is not possible. If you need authentication support let me know and I will push a fix in for that as well. I am trying to keep this first version as simple as possible till I know it works.

**Comment by farnulfo** [comment]
Hi,

It works with an unauthenticated proxy with some caveats:
- required a modification of the java-api pom to use 1.0.3 version of net.ossindex:heuristic-version instead of A.0.3-SNAPSHOT which doesn't exist on maven central
https://github.com/OSSIndex/java-api/blob/fb328848643ac839b4e8a7c29a50d64d049a8fe4/pom.xml#L144
- on project with a lot of dependencies we hit read time out exception. Fine on small project . May be 5s is too low if you send all the dependecies in one shot ?

**Comment by OSSIndex-Admin** [comment]
Whoops. I will fix both those issues tonight and update. You are surely correct on both issues.

**Comment by OSSIndex-Admin** [comment]
Alright, you should see fixes for both issues in the new version. Note that the timeout can be increased via environment variable if the default is not long enough, but it almost certainly is (I increased it to 60s). I believe somewhere around there the server will give up and I will have to do some more concentrated optimization efforts.

Anyhow, just in case, there are three environment variables you could set to muck about with the timeouts; the first is the most interesting one since it configures how long data has to show up.

* OSSINDEX_PROXY_SOCKET_TIMEOUT
* OSSINDEX_PROXY_CONNECT_TIMEOUT
* OSSINDEX_PROXY_CONNECTION_REQUEST_TIMEOUT

Thanks for the help!

**Comment by NancyChunlan** [comment]
Sorry for late reply. After verification, it works fine for us to set the proxy in maven settings.xml.
By the way, we used proxy which doesn't require authentication.
Thanks very much for your support.

**Comment by NancyChunlan** [comment]
And by the way, seems the plugin also scanned 3pps in test scope, is it possible to add new parameters to specify the scope? Thanks!

**Comment by OSSIndex-Admin** [comment]
Sorry I have not responded earlier. Many things have been lost in the shuffle in the past couple of months, but I should be catching up on them shortly. I will definitely look into adding scoping.

**Comment by OSSIndex-Admin** [comment]
I have added a new issue to track this feature: https://github.com/OSSIndex/ossindex-maven-plugin/issues/18

**Comment by OSSIndex-Admin** [comment]
With the original issue resolved, and a new issue created, I am now closing this issue.

**Comment by NancyChunlan** [comment]
The proxy works now. Thanks very much for your fixing.

**Comment by amasu** [comment]
Hi,
Any plan to support proxy authentication in coming releases?
Should I open a new issue for that?
Thanks

**Comment by amasu** [comment]
Hi,
Thank you for your reply. Looking forward to test the new plugin then :)

**Comment by amasu** [comment]
Hi,

Sry I was on vacation... 
Just tested and it works like a charm :) Thank you for your support!

**Comment by ken-duck** [comment]
Awesome! Glad its working and thanks for the feedback!
