### ISSUE TITLE
Compile scoped dependencies report vulnerability bug 

### ISSUE THREAD

**Issue by stolp** [OSSIndex/ossindex-maven-plugin#8]
I am getting errors like the following in a sub module of my project:

> [ERROR]
> [ERROR] --------------------------------------------------------------
> [ERROR] org.codehaus.groovy:groovy-all:2.4.0  [VULNERABLE]
> [ERROR]   required by ch.qos.logback:logback-classic:1.2.3
> [ERROR] 3 known vulnerabilities, 1 affecting installed version
> [ERROR]
> [ERROR] [CVE-2015-3253]  Improper Neutralization of Special Elements in Output Used by a Downstream Component ("Injection")
> [ERROR] https://ossindex.net/resource/cve/7149506119
> [ERROR] The MethodClosure class in runtime/MethodClosure.java in Apache Groovy 1.7.0 through 2.4.3 allows remote attackers to execute arbitrary code or cause a denial of service via a crafted serialized object.
> [ERROR]
> [ERROR] --------------------------------------------------------------
> [ERROR]

groovy-all is a compile time dependency of logback-classic (<scope>compile</scope>) and therefore will not be part of the resulting project.

I think the plugin must not complain about this dependency and compile scoped dependencies in general. Same probably goes for scope 'provided' but I have not tested this.

**Comment by OSSIndex-Admin** [comment]
Thank you for the report. I will look in to excluding compile-time dependencies, in the meanwhile you can ignore the package using the `-Daudit.ignore=org.codehaus.groovy:groovy-all` option (or `-Daudit.ignore=org.codehaus.groovy:groovy-all:2.4.0` to ignore the specific version.

**Comment by farnulfo** [comment]
Hi,
I was trying to help with this issue and after some tests, I think the issue is not about excluding compile scoped but only "optional" compile scoped.

I made a test with a simple projet which included org.apache.struts:struts2-core:2.3.32 as a dependency.
When running OSS Index maven plugin, org.apache.velocity:velocity-tools:1.3 is listed as a dependency and analyzed but velocity is an optional dependency to struts2-core and it was not included in my project : it shouldn't be audited.

May be OSS Index should get dependencies list as the same way as the maven-dependency-plugin:tree goal which list only dependency that would go in project.

Source code : 
https://maven.apache.org/plugins/maven-dependency-plugin/xref/org/apache/maven/plugins/dependency/tree/TreeMojo.html

**Comment by OSSIndex-Admin** [comment]
Slick. Thanks for the sample code. I should be able to give this a shot later on this evening.

**Comment by OSSIndex-Admin** [comment]
Ha. I rewrote the dependency code based on @farnulfo 's suggestion, and it indeed appears that all dependency issues are handled automagically for me. It also simplified the code significantly since I am no longer importing aether separately to do dependency calculation (it uses the built in version instead.)

I am running through a bit more testing, and should be getting a new version uploaded shortly.

**Comment by OSSIndex-Admin** [comment]
The fix should find its way to maven central tonight.

**Comment by OSSIndex-Admin** [comment]
Many thanks @stolp for the report, and @farnulfo for the added help with the issue (and sample code link). It appears to be on maven central and my tests are passing. Let me know if the solution has not been resolved satisfactorily.

**Comment by stolp** [comment]
Works as expected for me now. Thanks!
